# RoboDomo CI

aliases:
  - &restore-yarn-cache
    key: v1-yarncache-{{ checksum "yarn.lock" }}
  - &restore-npm-cache
    key: v1-node-modules-{{ checksum "yarn.lock" }}
  - &restore-webpack-cache
    key: v1-webpackcache-{{ checksum "yarn.lock" }}

defaults: &defaults
  working_directory: /home/circleci/repo
  docker:
    - image: circleci/node:12

version: 2.1
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-git-{{ .Branch }}-{{ .Revision }}
            - v1-git-{{ .Branch }}-
            - v1-git-
      - checkout
      - restore_cache: *restore-yarn-cache
      - run:
          name: Install Node modules
          command: yarn install --frozen-lockfile
      - run:
          name: Prune dependencies
          command: |
            curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash
            ./bin/node-prune
            # remove webpack cache if there
            rm -rdf node_modules/.cache
            # git garbage collect
            git gc
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - save_cache:
          key: v1-yarncache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build-pwa:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - restore_cache: *restore-webpack-cache
      - run:
          name: Build Project
          command: yarn build
      - save_cache:
          key: v1-webpackcache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/.cache

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Run ESLint
          command: yarn eslint src && yarn --cwd ./e2e-tests test:lint

  run-pwa:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Run Project
          command: yarn start
          background: true
      - run:
          name: Wait for project to start
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3032/graphql
            :

  test-pwa:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run e2e tests
          command: yarn --cwd ./e2e-tests test:bs_cloud -- --baseUrl=http://bs-local.com:3000 --user=sergiupopescu2 --key=GnvL9ihmskGTxHsmkyXf --cucumberOpts.tagExpression='@automated and @smoke'

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-pwa:
          requires:
            - install-dependencies
      - run-pwa:
          requires:
            - install-dependencies
            - build-pwa
      - test-pwa:
          requires:
            - install-dependencies
